#FROM ghcr.io/graalvm/graalvm-ce:ol8-java17-22.1.0
#FROM ghcr.io/graalvm/graalvm-ce:ol7-java17-22.1.0
#FROM ghcr.io/graalvm/graalvm-ce:ol8-java11-22.1.0
FROM ghcr.io/graalvm/graalvm-ce:ol7-java11-22.1.0

WORKDIR /java/src

RUN gu install native-image

COPY . .

CMD ["tail", "-f", "/dev/null"]